### ISSUE TITLE
No LICENSE for github.com/equinox-io/equinox?

### ISSUE THREAD

**Issue by anthonyfok** [equinox-io/equinox#6]
No LICENSE or LICENSE.md file is included for github.com/equinox-io/equinox,
nor is there any indication of github.com/equinox-io/equinox's license anywhere in README.md or in the source code.

(The LICENSE files included third-party libraries in "internal" don't count.)

This prevents github.com/equinox-io/equinox from being packaged by Linux distributions like Debian or Fedora.

Thank you for your kind consideration.

**Comment by kyleconroy** [comment]
Sorry this took so long to resolve. The code is now licensed under the MIT license.

**Comment by henvic** [comment]
Thanks, Kyle!
